# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "李源浚"
description              : "山东大学人工智能学院硕士研究生"
repository               : "MaoMaoLYJ/MaoMaoLYJ.github.io"  # 替换为你的GitHub仓库名称
google_scholar_stats_use_cdn : false

# google analytics
google_analytics_id      :  # 如果你有Google Analytics ID，可以在这里填写

# SEO Related
google_site_verification :  # 如果你有Google Search Console的验证代码，可以在这里填写
bing_site_verification   :  # 如果你有Bing Webmaster的验证代码，可以在这里填写
baidu_site_verification  :  # 如果你有百度站长平台的验证代码，可以在这里填写

# Site Author
author:
  name             : "李源浚"
  avatar           : "images/me.jpg"  # 替换为你的个人照片路径
  bio              : "山东大学人工智能学院硕士研究生"
  location         : "山东济南"
  employer         : "山东大学"
  pubmed           : 
  googlescholar    :   # 替换为你的Google Scholar ID
  email            : "15214855@cumt.edu.cn"
  researchgate     : 
  uri              : 
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "MaoMaoLYJ"  # 替换为你的GitHub用户名
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : 
  dblp             : 
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development